fix: 젠킨스 도커 컴포즈 수정

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -30,7 +30,7 @@ pipeline {
                         echo "🧹 Cleaning up old Docker containers..."
                         dir('frontend') {
                             sh '''
-                            docker-compose down --rmi all --volumes --remove-orphans || true
+                            docker compose down --rmi all --volumes --remove-orphans || true
                             docker rmi frontend_admin_image:latest frontend_service_image:latest || true
                             '''
                         }
@@ -50,7 +50,7 @@ pipeline {
                         echo "🚀 Deploying Docker containers..."
                         dir('frontend') {
                             sh '''
-                            docker-compose up -d --build || (echo "❌ Deployment Failed!" && exit 1)
+                            docker compose up -d --build || (echo "❌ Deployment Failed!" && exit 1)
                             '''
                         }
                         echo "✅ Deployment 완료!"
