feat: pnpm-lock.yaml 파일 수정

diff --git a/apps/service/Dockerfile b/apps/service/Dockerfile
--- a/apps/service/Dockerfile
+++ b/apps/service/Dockerfile
@@ -21,10 +21,10 @@ RUN apk add --no-cache libc6-compat
 RUN npm install -g pnpm
 WORKDIR /app
 COPY --from=builder /app/out/json/ .
-RUN pnpm install
+RUN pnpm install --frozen-lockfile --recursive
 RUN ls -l /app/node_modules
 COPY --from=builder /app/out/full/ .
-
+RUN ls -l /app/node_modules/@nova/ui || (echo "❌ @nova/ui not found!" && exit 1)
 RUN rm -rf .next
 RUN pnpm turbo build
 
